### ISSUE TITLE
"Exception ticking world" when Fir leaves disappear

### ISSUE THREAD

**Issue by LordOfTheWeebs** [SpudsMods/NewWorld#3]
Whenever the leaves from the Fir tree disappear, the game crashes with Exception ticking world error: "java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0." I originally thought it was due to a combination of mods since I have it in my personal modpack, but I tested it on a clean install with only the required mods of Fabric API and TerraBlender.

[crash-2023-08-14_16.14.39-server.txt](https://github.com/SpudsMods/NewWorld/files/12339279/crash-2023-08-14_16.14.39-server.txt)
[latest.log](https://github.com/SpudsMods/NewWorld/files/12339281/latest.log)

**Comment by ArshiaDPG** [comment]
Thank you for bringing this to our attention.
I've found the problem and will try to release a fix ASAP.
